import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>SNS</title>
        <meta name="description" content="GEnerated by create next app"></meta>
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
    </>

  );
}
